// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4e8DJqhV9HZr70f70_70CgcMr3Dibj_I',
    appId: '1:419469942931:web:774081d655781ba71a6d66',
    messagingSenderId: '419469942931',
    projectId: 'flutter-payflow-demo',
    authDomain: 'flutter-payflow-demo.firebaseapp.com',
    storageBucket: 'flutter-payflow-demo.appspot.com',
    measurementId: 'G-K3BDS3BCB2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBo8Jg1qd0zb4DpiWiZ1ptJQmn7vJxeXc0',
    appId: '1:419469942931:android:eddc3f88fc8cc3681a6d66',
    messagingSenderId: '419469942931',
    projectId: 'flutter-payflow-demo',
    storageBucket: 'flutter-payflow-demo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDk6aWPt1vtg3s6tV3KTgqTskEAwf_s51g',
    appId: '1:419469942931:ios:e2be78fdd6f5a56a1a6d66',
    messagingSenderId: '419469942931',
    projectId: 'flutter-payflow-demo',
    storageBucket: 'flutter-payflow-demo.appspot.com',
    androidClientId: '419469942931-q1pn8jf4glponc2nkr9ifg1aabb9s8ci.apps.googleusercontent.com',
    iosClientId: '419469942931-cc84ev1oms9drbq56u7geud2o4l7btpm.apps.googleusercontent.com',
    iosBundleId: 'com.example.payflow',
  );
}
